# -*- coding: utf-8 -*-
"""Preprocessing_microbiome_ASD.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XvyBDQiA_hmA36LDpGte9-cvCrHhHo7P
"""

pip install scikit-bio

from google.colab import drive
drive.mount('/content/drive')

from platform import python_version
import pandas as pd
import numpy as np
import skbio
from skbio.stats.composition import clr

import re

genus=pd.read_csv("/content/drive/My Drive/GSE113690_Autism_16S_rRNA_OTU_assignment_and_abundance.csv")

genus

zero_cols = genus.columns[(genus == 0).all()]
print(zero_cols)

taxa =genus[['OTU', 'taxonomy']].set_index('OTU')
genus_T =genus.drop('taxonomy', axis=1).set_index('OTU').transpose()
target =genus_T.index.to_list()
binary_target = np.array([1 if t.startswith('A') else 0 for t in target ])


genus_T=genus_T+1
total_species =genus_T.sum(axis = 1)
abs_abundance = 31757
pd_rel_abundance =genus_T.div(total_species,axis=0)

pd_rel_abundance['Diagnosis']=binary_target

pd_rel_abundance.to_csv("/content/drive/My Drive/data_autismo_relative.csv")

df_clr=pd.DataFrame(clr(pd_rel_abundance),columns=pd_rel_abundance.columns)

df_clr

df_clr['Diagnosis']=binary_target

df_clr.to_csv('/content/drive/My Drive/df_autismo_clr.csv')

df_clr

