# -*- coding: utf-8 -*-
"""Preprocessing_microbiome_CRC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17DuZD_pnB00awtW7TzLBbHaaxBX9YVw0
"""

pip install scikit-bio

from google.colab import drive
drive.mount('/content/drive')

from platform import python_version
import pandas as pd
import numpy as np
import skbio
from skbio.stats.composition import clr

import re

genus=pd.read_csv("/content/drive/My Drive/genus.csv")

metadata=pd.read_csv("/content/drive/My Drive/metadata.csv")

genus

genus=genus.drop(' uncultured',axis=1)

zero_cols = genus.columns[(genus == 0).all()]
print(zero_cols)

genus = genus.drop(zero_cols, axis=1)

metadata

df_completo=pd.merge(genus,metadata,left_on='SampleID',right_on='SampleID')

df_completo

df_completo.iloc[:,1:458]

"""#Pseudonormalization
We add one to the genus abundance data before performing CLR normalization
"""

df_completo.iloc[:,1:458]=df_completo.iloc[:,1:458]+1
df_completo.iloc[:,1:458]=(df_completo.iloc[:,1:458]).div(df_completo.iloc[:,1:458].sum(axis=1), axis=0)

df_completo.iloc[:,1:462]

df_completo.to_csv("/content/drive/My Drive/df_relative.csv")

df_completo.iloc[:,1:458]=pd.DataFrame(clr(df_completo.iloc[:,1:458]),columns=df_completo.iloc[:,1:458].columns)

df_completo.iloc[:,1:458]

"""# Dataframe completo con normalizzazione CLR"""

df_completo

df_completo.to_csv('/content/drive/My Drive/df_completo_filtrato_tesi.csv', index=False)

